# Generated by Django 5.1.1 on 2024-11-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_usuario_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True),
        ),
    ]
