# Generated by Django 5.1.1 on 2024-11-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_usuario_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_empresa',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
