# Generated by Django 5.1.1 on 2024-09-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_dosis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_edad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_enfermedad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_intervalo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroDosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_numero_dosis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Refuerzos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_Refuerzos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_vacuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ViaSitioAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_via_sitio_aplicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.dosis')),
                ('edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.edad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.enfermedad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
                ('intervalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.intervalo')),
                ('numero_dosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.numerodosis')),
                ('refuerzos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.refuerzos')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.vacuna')),
                ('via_sitio_aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.viasitioaplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='DosisAplicadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dosis_aplicada', models.IntegerField()),
                ('fecha_aplicacion', models.DateField()),
                ('siguiente_dosis', models.CharField(choices=[('aplica', 'Aplica'), ('no aplica', 'No Aplica')], max_length=15)),
                ('fecha_siguiente_dosis', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('esquema_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.esquemavacunas')),
            ],
        ),
    ]
