# Generated by Django 5.1.1 on 2024-11-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0002_remove_dosisaplicadas_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refuerzos',
            old_name='esquema_Refuerzos',
            new_name='esquema_refuerzos',
        ),
    ]
