# Generated by Django 5.1.1 on 2024-11-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0003_rename_esquema_refuerzos_refuerzos_esquema_refuerzos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=100, unique=True)),
                ('vacuna', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('numero_dosis', models.IntegerField()),
                ('edad', models.CharField(max_length=100)),
                ('intervalo', models.CharField(max_length=100)),
                ('via_sitio_aplicacion', models.CharField(max_length=100)),
                ('refuerzos', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='enfermedad',
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='intervalo',
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='numero_dosis',
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='refuerzos',
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='vacuna',
        ),
        migrations.RemoveField(
            model_name='esquemavacunas',
            name='via_sitio_aplicacion',
        ),
        migrations.AddField(
            model_name='esquemavacunas',
            name='vacunas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacunacion.vacunas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dosis',
        ),
        migrations.DeleteModel(
            name='Edad',
        ),
        migrations.DeleteModel(
            name='Enfermedad',
        ),
        migrations.DeleteModel(
            name='Intervalo',
        ),
        migrations.DeleteModel(
            name='NumeroDosis',
        ),
        migrations.DeleteModel(
            name='Refuerzos',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
        migrations.DeleteModel(
            name='ViaSitioAplicacion',
        ),
    ]
