# Generated by Django 5.1.1 on 2024-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0004_vacunas_remove_esquemavacunas_dosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunas',
            name='edad',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vacunas',
            name='intervalo',
            field=models.CharField(max_length=500),
        ),
    ]
