# Generated by Django 5.1.1 on 2024-11-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0006_esquemavacunas_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esquemavacunas',
            name='fecha_creacion',
            field=models.DateField(default='2024-11-05'),
            preserve_default=False,
        ),
    ]
