# Generated by Django 5.1.1 on 2024-11-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0007_esquemavacunas_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemavacunas',
            name='fecha_aplicacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='esquemavacunas',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
