# Generated by Django 5.1.1 on 2024-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0008_alter_esquemavacunas_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemavacunas',
            name='fecha_aplicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='esquemavacunas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='esquemavacunas',
            name='fecha_siguiente_dosis',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
