# Generated by Django 5.1.1 on 2024-11-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0010_alter_esquemavacunas_fecha_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemavacunas',
            name='fecha_aplicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
