# Generated by Django 5.1.1 on 2024-11-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0013_alter_esquemavacunas_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemavacunas',
            name='fecha_aplicacion',
            field=models.DateTimeField(),
        ),
    ]
