# Generated by Django 5.1.1 on 2024-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0014_alter_esquemavacunas_fecha_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemavacunas',
            name='siguiente_dosis',
            field=models.CharField(choices=[('Aplica', 'Aplica'), ('No aplica', 'No Aplica')], max_length=15),
        ),
    ]
