# Generated by Django 5.1.1 on 2024-09-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero_persona',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenimo'), ('otro', 'Otro')], default='masculino', max_length=15),
            preserve_default=False,
        ),
    ]
