# Generated by Django 5.1.1 on 2024-09-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_persona_genero_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nombre_empresa',
        ),
    ]
