# Generated by Django 5.1.1 on 2024-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_empresa_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
