# Generated by Django 5.1.1 on 2024-11-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_acudiente_telefono_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='nombre_acudiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='numero_identificacion_acudiente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='tipos_acudiente',
            field=models.CharField(blank=True, choices=[('padre', 'Padre'), ('madre', 'Madre'), ('familiar', 'Familiar')], max_length=15, null=True),
        ),
    ]
