# Generated by Django 5.1.1 on 2024-11-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_acudiente_nombre_acudiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
            preserve_default=False,
        ),
    ]
